[package]
name = "cacheline-ef"
version = "0.1.0"
edition = "2021"

[dependencies]
common_traits = "0.11.0"
epserde = { version = "0.8.0", optional = true }
mem_dbg = "0.3.0"

[features]
epserde = ["dep:epserde"]

[dev-dependencies]
rand = "0.9.0"
